pickme-semi/semi-pickme

src/com/user/model/vo/User.java
=> user vo update

src/com/pick/controller/PickMainServlet.java, src/com/pick/controller/PickSelectOneServlet.java, src/com/pick/controller/PickUploadServlet.java, src/com/pick/model/dao/PickDao.java, src/com/pick/model/service/PickService.java, web/views/pickpage/PickMain.jsp, web/views/pickpage/PickSub.jsp, web/views/pickpage/PickUpload.jsp
pick 메인,업로드 페이지 카테고리 선택부분 ui변경 mvc와 서블릿 일부 내용 추가했으나 아직 작동단계 아님. 저녁쯤 추가로 작업 더 할 예정.
=> pick 서블릿 파일이름 변경, ui 일부 변경,

src/com/user/controller/UserJoinServlet.java, web/views/common/header.jsp, web/views/profile/myPage.jsp
=> 회원정보수정페이지 UI + 기능추가

web/views/pickpage/PickMain.jsp
=> PickMain 만우선 uo

src/com/pick/controller/PickResultInsertServlet.java, src/com/pick/model/dao/PickResultDao.java, src/com/pick/model/service/PickResultService.java, src/com/pick/model/vo/PickResult.java, src/config/pick-me.properties, web/views/pickpage/PickMain.jsp
Pick Result 관련 MVC 생성 후 픽메인 은 수정할예정입니다.
그외 사항 전부다 예외처리해놨습니다.
=> PickResult 관련

web/views/profile/myPage.jsp
=> profile 기본 사진

src/com/user/controller/UserLoginServlet.java, src/com/user/controller/UserPassResetServlet.java, src/com/user/controller/UserReissueServlet.java, web/views/user/UserJoinForm.jsp, web/views/user/UserLoginForm.jsp, web/views/user/UserPassReset.jsp, web/views/user/UserPassSearchForm.jsp
=> 비밀번호 & 로그인 페이지 변경

src/com/pick/controller/PickUploadServlet.java, web/views/pickpage/PickMain.jsp, web/views/pickpage/PickUpload.jsp
날짜 기본값은 현재시간+1달 정도로 하려는데 아직 테스트 중.
=> 업로드 폼 값 전부 넣어야 업로드 가능하게 설정, 첨부파일 확장자 제한.

src/com/profile/controller/MyPageUpdateServlet.java, src/com/profile/model/dao/ProfileDao.java, src/com/profile/model/service/ProfileService.java, src/com/user/encrypt/EncryptWrapper.java, src/config/profile-query.properties, src/config/user-query.properties, web/views/profile/myPage.jsp, web/views/user/UserJoinForm.jsp, web/views/user/UserLoginForm.jsp, web/views/user/UserTerms.jsp
회원정보 수정시 필수값이 널일경우 수정(0)
이메일 중복체크 이슈(0)
관심분야 삽입 삭제 status 수정(0)
비밀번호 정규식 삽입(0)
------------------------------------------
회원가입 로그인 마이페이지 (UI수정)
그런데 왜인지 모르게...비밀번호와 비밀번호 확인 경고 메시지가 안뜸..
=> 회원가입, 마이페이지 부분수정

src/com/pick/controller/PickUploadServlet.java, web/views/pickpage/PickUpload.jsp
=> 카테고리 안받아도 DB 저장되게 설정, 파일업로드 수정, pick 업로드시 마감 날짜 기본값 들어가게 설정.

src/com/profile/controller/MyPageUpdateServlet.java, web/views/profile/myPage.jsp
패스워드 입력 안해도 넘어가는 경우 , 카테고리 null 일 때 오류나는 거
=> 회원정보페이지 수정

src/com/point/model/vo/Point.java, src/com/profile/controller/MyPicksServlet.java, src/com/profile/controller/UserPageServlet.java, src/com/profile/model/dao/ProfileDao.java, src/com/profile/model/service/ProfileService.java, src/config/profile-query.properties, web/views/profile/myPage.jsp, web/views/profile/myPicks.jsp, web/views/profile/userPage.jsp
회원정보 수정 에러 잡기
, 포인트
, 유저페이지 픽 결과 추가
=> 회원정보 수정 에러 잡기, 포인트 , 유저페이지 픽 결과 추가

web/resources/css/swell-2472ebd5fc.css, web/views/profile/myPicks.jsp
=> My Pick UI 수정중

src/com/pick/controller/PickSelectOneServlet.java, src/com/pick/model/dao/PickDao.java, src/config/pick-me.properties, web/views/pickpage/PickMain.jsp, web/views/pickpage/PickSub.jsp, web/views/pickpage/PickUpload.jsp
=> pick upload ui 수정중, pick상세 페이지 구현중..

src/com/pick/model/dao/PickDao.java, src/com/pick/model/vo/PickMe.java, src/config/pick-me.properties, web/views/pickpage/PickMain.jsp
=> 우선 커밋합니다.  pick page 프로필작성

web/views/profile/followerList.jsp, web/views/search/SearchUserList.jsp
=> searchList 수정

src/com/profile/controller/MyPageUpdateServlet.java, src/config/pick-me.properties, web/views/pickpage/PickMain.jsp
=> 6개 넘기는거 무한반복했습니당

src/com/pick/controller/PickSelectOneServlet.java, src/com/pick/model/dao/PickDao.java, src/com/reply/controller/CommentDeleteServlet.java, src/com/reply/controller/CommentInsertServlet.java, src/com/reply/controller/CommentUpdateServlet.java, src/com/reply/model/dao/PickCommentDao.java, src/com/reply/model/service/PickCommentService.java, src/com/reply/model/vo/PickComment.java, src/config/comment.properties, web/views/pickpage/PickSub.jsp
=> 상세페이지 댓글기능 구현

web/views/pickpage/PickSub.jsp, web/views/pickpage/PickUpload.jsp
일부 기능(댓글수정 등)이 제대로 동작안함. 내일 수정해야됨.
=> 상세페이지에서 사진 클릭시 결과값 저장 기능 추가, ui 수정.

web/views/stats/statsTotalList.jsp
=> 통계 리스트를 정리해보려다가 실패했음

src/com/stats/controller/StatsOneList.java, src/com/stats/controller/StatsResult.java, src/com/stats/model/dao/StatsDao.java, src/com/stats/model/service/StatsService.java, src/config/stats.properties, web/views/stats/statsOneList.jsp, web/views/stats/statsTotalList.jsp
=> 통계 세부페이지 수정

web/views/profile/myPicks.jsp, web/views/profile/userPage.jsp
=> userPage ui 한줄소개 ui
